import {leadSchema} from '@/lib/lead-schema';import {eq} from 'drizzle-orm';import {getDb} from '@/db';import {clients,leads} from '@/db/schema';
const requests=new Map<string,{count:number;until:number}>();
function json(data:unknown,status=200,headers:Record<string,string>={}){return Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}})}
export async function GET(request:Request){const token=crypto.randomUUID();return json({token},200,{'Set-Cookie':'lead-csrf='+token+'; Path=/api/leads; HttpOnly; SameSite=Strict; Max-Age=1800'+(new URL(request.url).protocol==='https:'?'; Secure':'')})}
export async function POST(request:Request){const reqOrigin=request.headers.get('origin');if(!reqOrigin||reqOrigin!==new URL(request.url).origin)return json({error:'Invalid request origin.'},403);const cookie=request.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith('lead-csrf='))?.slice(10);if(!cookie||cookie!==request.headers.get('x-csrf-token'))return json({error:'Your form session expired. Reload and try again.'},403);
const now=Date.now();for(const[k,v]of requests)if(v.until<now)requests.delete(k);const key='mock';const limit=requests.get(key)||{count:0,until:now+60000};if(limit.count>=30)return json({error:'Too many test submissions. Please try again in a minute.'},429,{'Retry-After':'60'});limit.count++;requests.set(key,limit);
if(process.env.LEAD_MODE&&process.env.LEAD_MODE!=='mock')return json({error:'Live lead delivery is not configured. Please contact the site administrator.'},503);
try{const reader=request.body?.getReader();if(!reader)return json({error:'Missing form data.'},400);const chunks:Uint8Array[]=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>2200000){await reader.cancel();return json({error:'Upload exceeds the 2 MB limit.'},413)}chunks.push(value)}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length}const form=await new Response(bytes,{headers:{'Content-Type':request.headers.get('content-type')||''}}).formData();const parsed=leadSchema.safeParse(Object.fromEntries([...form.entries()].filter(([k])=>k!=='resume')));if(!parsed.success)return json({error:parsed.error.issues.map(i=>i.message).join(' ')},422);if(parsed.data.website)return json({error:'Submission rejected.'},400);if(parsed.data.formType==='career'){const f=form.get('resume');if(!(f instanceof File)||f.size===0||f.size>2097152||f.type!=='application/pdf'||!f.name.toLowerCase().endsWith('.pdf'))return json({error:'Upload a PDF résumé under 2 MB.'},422);const sig=new TextDecoder().decode((await f.arrayBuffer()).slice(0,5));if(sig!=='%PDF-')return json({error:'The uploaded file is not a valid PDF.'},422);}
const referer=request.headers.get('referer')||'';const match=new URL(referer||request.url).pathname.match(/^\/client\/([^/]+)/);if(match&&process.env.DATABASE_URL){const client=(await getDb().select({id:clients.id}).from(clients).where(eq(clients.slug,match[1])).limit(1))[0];if(!client)return json({error:'Unknown client website.'},404);const id=crypto.randomUUID(),url=new URL(referer);await getDb().insert(leads).values({id,clientId:client.id,type:parsed.data.formType.replace('-','_').toUpperCase() as 'CONTACT'|'QUOTE'|'SITE_VISIT'|'CALLBACK',name:parsed.data.name,phone:parsed.data.phone,email:parsed.data.email||null,projectType:parsed.data.projectType||null,location:parsed.data.location||null,area:parsed.data.area||null,budget:parsed.data.budget||null,message:parsed.data.message||null,source:'website',pageUrl:url.pathname,utmSource:url.searchParams.get('utm_source'),utmMedium:url.searchParams.get('utm_medium'),utmCampaign:url.searchParams.get('utm_campaign'),utmTerm:url.searchParams.get('utm_term'),utmContent:url.searchParams.get('utm_content')});return json({ok:true,id,message:'Your enquiry has been received.'},201)}
return json({ok:true,mode:'mock',id:crypto.randomUUID(),message:'Test receipt only. Data discarded; no lead was sent.'},201);
}catch{return json({error:'Invalid form data. Please try again.'},400)}}
