'use client';
import {useEffect,useMemo,useState} from 'react';
type Item={name:string;slug?:string;shortDescription?:string;description?:string;category?:string;location?:string;enabled:boolean;featured:boolean;sortOrder?:number};
type Draft={name:string;slug:string;phone:string;whatsapp:string;email:string;tagline:string;description:string;logoUrl:string;faviconUrl:string;heroUrl:string;city:string;district:string;state:string;country:string;pincode:string;primaryColor:string;secondaryColor:string;accentColor:string;theme:'corporate'|'luxury'|'industrial'|'contractor'|'realestate'|'minimal';services:Item[];projects:Item[]};
const themes=[['corporate','Structured and professional'],['luxury','Elegant and image-led'],['industrial','Technical and information-rich'],['contractor','Direct and conversion-focused'],['realestate','Project and location focused'],['minimal','Clean and lightweight']] as const;
const blank:Draft={name:'',slug:'',phone:'',whatsapp:'',email:'',tagline:'',description:'',logoUrl:'',faviconUrl:'',heroUrl:'',city:'Bokaro',district:'Bokaro',state:'Jharkhand',country:'India',pincode:'',primaryColor:'#F59E0B',secondaryColor:'#111827',accentColor:'#FFFFFF',theme:'corporate',services:[],projects:[]};
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,62);
export function AdminClientBuilder({clientId}:{clientId?:string}){
 const [draft,setDraft]=useState<Draft>(blank),[step,setStep]=useState(0),[state,setState]=useState(clientId?'Loading…':'Unsaved changes'),[busy,setBusy]=useState(false),[id,setId]=useState(clientId);
 const valid=useMemo(()=>Boolean(draft.name&&draft.slug&&draft.theme&&(draft.phone||draft.email||draft.whatsapp)&&(draft.services.length||draft.projects.length)),[draft]);
 useEffect(()=>{const url=clientId?'/api/admin/clients/'+clientId:'/api/admin/session';fetch(url).then(async r=>{if(r.status===401||r.status===403){location.replace('/admin/login');return null}const data=await r.json() as {authenticated?:boolean;client?:Partial<Draft>;error?:string};if(!r.ok)throw new Error(data.error||'Unable to load client.');if(!clientId){if(!data.authenticated)location.replace('/admin/login');return null}if(!data.client)throw new Error('Unable to load client.');return data.client}).then(client=>{if(!client)return;const textKeys=['name','slug','phone','whatsapp','email','tagline','description','logoUrl','faviconUrl','heroUrl','city','district','state','country','pincode','primaryColor','secondaryColor','accentColor'] as const;const normalized={...blank,...client,services:client.services||[],projects:client.projects||[]};for(const key of textKeys)normalized[key]=client[key]??blank[key];setDraft(normalized as Draft);setState('Saved')}).catch(error=>setState(error instanceof Error?error.message:'Unable to load client.'))},[clientId]);
 function set<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(v=>({...v,[key]:value}));setState('Unsaved changes')}
 function add(kind:'services'|'projects'){const name=prompt(kind==='services'?'Service name':'Project name')?.trim();if(name)set(kind,[...draft[kind],{name,enabled:true,featured:false,sortOrder:draft[kind].length}])}
 async function save(){setBusy(true);setState('Saving…');try{const r=await fetch(id?'/api/admin/clients/'+id:'/api/admin/clients',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const d=await r.json() as {id?:string;error?:string};if(!r.ok||!d.id)throw new Error(d.error||'Save failed');setId(d.id);setState('Draft saved');if(!id)history.replaceState(null,'','/admin/clients/'+d.id)}catch(error){setState(error instanceof Error?error.message:'Save failed')}finally{setBusy(false)}}
 async function upload(file:File){if(!id){setState('Save the client before uploading images.');return}setState('Preparing upload…');const response=await fetch('/api/admin/uploads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:id,name:file.name,type:file.type,size:file.size})});const data=await response.json() as {uploadUrl?:string;publicUrl?:string|null;error?:string};if(!response.ok||!data.uploadUrl){setState(data.error||'Upload failed');return}const sent=await fetch(data.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!sent.ok){setState('Storage rejected the upload.');return}if(!data.publicUrl){setState('Uploaded, but S3_PUBLIC_BASE_URL is missing.');return}set('logoUrl',data.publicUrl);setState('Logo uploaded. Save the draft.')}
 async function publish(){if(!id){setState('Save the draft first.');return}setBusy(true);setState('Publishing…');try{const r=await fetch(`/api/admin/clients/${id}/publish`,{method:'POST'}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'Publish failed');setState('Website published')}catch(error){setState(error instanceof Error?error.message:'Publish failed')}finally{setBusy(false)}}
 const sections=['Company','Brand','Location','Services','Projects','Preview & publish'];
 return <div className="admin-wizard"><div className="wizard-steps">{sections.map((s,i)=><button key={s} className={i===step?'active':''} onClick={()=>setStep(i)}>{i+1}. {s}</button>)}</div><div className="admin-editor"><div className="admin-title"><div><p className="eyebrow">CLIENT WEBSITE</p><h1>{draft.name||'Create client'}</h1></div><span>{state}</span></div>
 {step===0&&<div className="form-grid"><Field label="Company name *" value={draft.name} onChange={v=>{set('name',v);if(!draft.slug)set('slug',slugify(v))}}/><Field label="Slug *" value={draft.slug} onChange={v=>set('slug',slugify(v))}/><Field label="Tagline" value={draft.tagline} onChange={v=>set('tagline',v)}/><Field label="Phone" value={draft.phone} onChange={v=>set('phone',v)}/><Field label="WhatsApp" value={draft.whatsapp} onChange={v=>set('whatsapp',v)}/><Field label="Email" value={draft.email} onChange={v=>set('email',v)}/></div>}
 {step===1&&<><div className="form-grid"><Field label="Logo URL" value={draft.logoUrl} onChange={v=>set('logoUrl',v)}/><label className="field">Upload logo<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file)}}/><small>{id?'JPEG, PNG, WebP or AVIF · max 10 MB':'Save the client first to enable uploads.'}</small></label><Field label="Favicon URL" value={draft.faviconUrl} onChange={v=>set('faviconUrl',v)}/>{(['primaryColor','secondaryColor','accentColor'] as const).map(k=><label className="field" key={k}>{k}<input type="color" value={draft[k]} onChange={e=>set(k,e.target.value)}/><input value={draft[k]} onChange={e=>set(k,e.target.value)}/></label>)}</div><h2>Choose website design</h2><div className="theme-cards">{themes.map(([name,desc])=><button key={name} className={draft.theme===name?'active':''} onClick={()=>set('theme',name)}><strong>{name}</strong><span>{desc}</span></button>)}</div></>}
 {step===2&&<div className="form-grid"><Field label="City" value={draft.city} onChange={v=>set('city',v)}/><Field label="District" value={draft.district} onChange={v=>set('district',v)}/><Field label="State" value={draft.state} onChange={v=>set('state',v)}/><Field label="Country" value={draft.country} onChange={v=>set('country',v)}/><Field label="Pincode" value={draft.pincode} onChange={v=>set('pincode',v)}/></div>}
 {(step===3||step===4)&&<ItemEditor title={step===3?'Services':'Projects'} items={step===3?draft.services:draft.projects} onAdd={()=>add(step===3?'services':'projects')} onChange={items=>set(step===3?'services':'projects',items)}/>} 
 {step===5&&<><div className="preview-frame" data-theme={draft.theme} style={{'--accent':draft.primaryColor,'--ink':draft.secondaryColor} as React.CSSProperties}><p className="eyebrow">LIVE DRAFT PREVIEW</p><h1>{draft.name||'Company name'}</h1><p>{draft.tagline||'Your company tagline'}</p><h2>Services</h2><p>{draft.services.map(s=>s.name).join(' · ')||'Add services'}</p><h2>Projects</h2><p>{draft.projects.map(p=>p.name).join(' · ')||'Add projects'}</p></div>{!valid&&<p className="error-message">Publication requires a company name, contact method, theme, slug, and at least one service or project.</p>}<p className="notice" role="status">{state}</p><div className="actions"><button className="button" disabled={busy} onClick={save}>{busy?'Working…':'Save draft'}</button>{id&&<a className="button outline admin-outline" href={`/client/${draft.slug}?preview=${id}`} target="_blank">Open full preview</a>}<button className="button" disabled={!valid||busy} onClick={publish}>{busy?'Working…':'Publish website'}</button></div></>}
 <div className="wizard-nav"><button disabled={step===0||busy} onClick={()=>setStep(v=>v-1)}>Back</button>{step<5&&<button className="button compact" onClick={()=>setStep(v=>v+1)}>Continue</button>}</div></div></div>
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="field">{label}<input value={value} onChange={e=>onChange(e.target.value)}/></label>}
function ItemEditor({title,items,onAdd,onChange}:{title:string;items:Item[];onAdd:()=>void;onChange:(v:Item[])=>void}){return <><div className="section-heading"><h2>{title}</h2><button className="button compact" onClick={onAdd}>Add {title.slice(0,-1)}</button></div>{!items.length&&<p className="notice">No {title.toLowerCase()} yet.</p>}{items.map((item,i)=><div className="admin-row" key={i}><input value={item.name} onChange={e=>onChange(items.map((v,n)=>n===i?{...v,name:e.target.value}:v))}/><label><input type="checkbox" checked={item.featured} onChange={e=>onChange(items.map((v,n)=>n===i?{...v,featured:e.target.checked}:v))}/> Featured</label><button onClick={()=>onChange(items.filter((_,n)=>n!==i))}>Remove</button></div>)}</>}
