import Link from './site-link';import type {FAQ,Project,Service,BlogPost,CompanyConfig,Testimonial} from '@/lib/types';import {Schema,origin} from '@/lib/seo';
export function SampleBadge({sample}:{sample?:boolean}){return sample?<span className="sample-badge">Sample content</span>:null}
export function Breadcrumbs({items}:{items:{label:string;href:string}[]}){return <><nav aria-label="Breadcrumb" className="breadcrumbs"><Link href="/">Home</Link>{items.map(i=><span key={i.href}> / <Link href={i.href}>{i.label}</Link></span>)}</nav><Schema value={{'@type':'BreadcrumbList',itemListElement:[{label:'Home',href:'/'},...items].map((i,n)=>({'@type':'ListItem',position:n+1,name:i.label,item:new URL(i.href,origin).href}))}}/></>}
export function PageHero({title,description,path,kicker='EXPLORE'}:{title:string;description:string;path:string;kicker?:string}){return <section className="page-hero"><div className="wrap"><Breadcrumbs items={[{label:title,href:path}]}/><p className="eyebrow">{kicker}</p><h1>{title}</h1><p>{description}</p></div></section>}
export function ProjectCard({project:p}:{project:Project}){return <article className="card"><Link href={'/projects/'+p.slug} className="card-image"><img src={p.gallery[0].src} alt={p.gallery[0].alt} width="768" height="512" loading="lazy"/><SampleBadge sample={p.isSample}/></Link><div className="card-body"><p className="eyebrow">{p.category} / {p.location.city}</p><h3><Link href={'/projects/'+p.slug}>{p.name}</Link></h3><p>{p.description.short}</p><span className="meta">{p.area.value.toLocaleString('en-IN')} {p.area.unit} · {p.isSample?'Illustrative concept':p.status+' · '+p.completionYear}</span></div></article>}
export function ServiceCard({service:s}:{service:Service}){return <article className="card service-card"><p className="eyebrow">{s.category}</p><h3><Link href={'/services/'+s.slug}>{s.title}</Link></h3><p>{s.shortDescription}</p><Link className="text-link" href={'/services/'+s.slug}>Explore service ↗</Link></article>}
export function BlogCard({post:p}:{post:BlogPost}){return <article className="card"><div className="card-body"><p className="eyebrow">{p.categories[0]} / {p.readingTime} MIN READ</p><h3><Link href={'/blog/'+p.slug}>{p.title}</Link></h3><p>{p.excerpt}</p><SampleBadge sample={p.isSample}/><Link className="text-link" href={'/blog/'+p.slug}>Read article ↗</Link></div></article>}
export function FAQSection({items}:{items:FAQ[]}){return <div className="faq-list">{items.map((f,i)=><details key={i}><summary>{f.question}</summary><p>{f.answer}</p></details>)}</div>}
export function Reviews({items,brand}:{items:Testimonial[];brand:CompanyConfig}){return <><div className="notice">These are sample testimonial layouts, not customer reviews or evidence of completed work.</div><div className="grid three">{items.map((t,i)=><blockquote className="card review" key={i}><SampleBadge sample={t.isSample}/><p>“{t.quote}”</p><cite>{t.clientName} · {t.location}</cite></blockquote>)}</div>{brand.googleBusinessUrl?<a className="text-link" href={brand.googleBusinessUrl} target="_blank" rel="noreferrer">View verified Google reviews ↗</a>:<p className="notice">A verified Google Business Profile has not been configured.</p>}</>}
export function Map({brand}:{brand:CompanyConfig}){return <div className="map"><iframe title={brand.isSample?'General service-area map, not a business address':'Business location'} src={brand.mapsEmbedUrl} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/><p className="meta">{brand.isSample?'General area map — no office location is claimed.':brand.address.street} <a className="text-link" href={brand.googleMapsUrl} target="_blank" rel="noreferrer">Open map ↗</a></p></div>}

