import Link from 'next/link';import type {SiteData} from './views';import {CTA} from './site-shell';import {ProjectCard,BlogCard,FAQSection,Reviews} from './content';
export function HomeView({data}:{data:SiteData}){const {brand,services,projects,posts,faqs,testimonials}=data;const featured=projects[0];return <>
<section className="hero"><div className="hero-image" style={{backgroundImage:'url('+brand.hero.image+')'}} role="img" aria-label="Illustrative architectural concept"/><div className="wrap hero-content"><p className="eyebrow">CONSTRUCTION WITH CLARITY · {brand.address.city.toUpperCase()}, {brand.address.state.toUpperCase()}</p><h1>{brand.hero.title}</h1><p className="hero-copy">{brand.hero.subtitle}</p><div className="actions"><Link className="button" href="/request-a-quote">Start your project ↗</Link><Link className="button outline" href="/projects">Explore our work</Link></div><div className="hero-note"><span>{featured?.name.toUpperCase()}</span><span>{brand.isSample?'Illustrative architecture · Sample concept':brand.tagline}</span></div></div></section>
<section className="principles wrap"><span>Built on a clear understanding.</span><p>Considered design</p><p>Defined scope</p><p>Thoughtful execution</p></section>
{brand.stats.length>0&&<section className="principles wrap">{brand.stats.map(s=><div key={s.label}><strong>{s.value}</strong><p>{s.label}</p>{s.isSample&&<small>Sample content</small>}</div>)}</section>}
<section className="section wrap"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Spaces with purpose.<br/>Details that matter.</h2></div><Link className="text-link" href="/projects">View all projects ↗</Link></div>
{featured&&<div className="feature-project"><Link href={'/projects/'+featured.slug} className="project-image"><img src={featured.gallery[0].src} alt={featured.gallery[0].alt} width="1536" height="1024" loading="lazy"/></Link><div><p className="eyebrow">{featured.category.toUpperCase()} / {featured.isSample?'SAMPLE CONCEPT':featured.location.city.toUpperCase()}</p><h3>{featured.name}</h3><p>{featured.description.short}</p><Link className="text-link" href={'/projects/'+featured.slug}>Explore the project ↗</Link></div></div>}
<div className="grid three">{projects.slice(1,4).map(p=><ProjectCard key={p.slug} project={p}/>)}</div></section>
<section className="section muted"><div className="wrap about-grid"><div><p className="eyebrow">02 / A CONSIDERED APPROACH</p><h2>More than a structure.<br/>A place to belong.</h2></div><div><p className="large-copy">Every project begins with listening. Understanding your site, your priorities and the way a space needs to work.</p><p>Explore an approach that brings planning, design coordination and construction together, with a written scope at each stage.</p><Link className="text-link" href="/about">Get to know us ↗</Link></div></div></section>
<section className="section wrap"><p className="eyebrow">03 / WHAT WE DO</p><h2>From the ground up.</h2><div className="service-list">{services.map((s,i)=><Link key={s.slug} href={'/services/'+s.slug}><span>0{i+1}</span><h3>{s.title}</h3><span aria-hidden>↗</span></Link>)}</div></section>
<section className="section muted"><div className="wrap"><p className="eyebrow">04 / THE CLIENT PERSPECTIVE</p><h2>Confidence at every step.</h2><Reviews items={testimonials.slice(0,3)} brand={brand}/></div></section>
{brand.features.blog&&<section className="section wrap"><div className="section-heading"><div><p className="eyebrow">05 / INSIGHTS</p><h2>A better-informed build.</h2></div><Link className="text-link" href="/blog">All insights ↗</Link></div><div className="grid three">{posts.slice(0,3).map(p=><BlogCard key={p.slug} post={p}/>)}</div></section>}
<section className="section wrap"><div className="about-grid"><div><p className="eyebrow">06 / COMMON QUESTIONS</p><h2>Clarity starts here.</h2><Link className="text-link" href="/faq">All questions ↗</Link></div><FAQSection items={faqs.slice(0,5)}/></div></section><CTA/></>}

