import {readFile,writeFile} from 'node:fs/promises';
import {createInterface} from 'node:readline/promises';
import {stdin as input,stdout as output} from 'node:process';

const target=new URL('../client.config.ts',import.meta.url);const args=process.argv.slice(2);const fromIndex=args.indexOf('--from');let config;
if(fromIndex>=0){const file=args[fromIndex+1];if(!file)throw new Error('Use --from clients/company.json');config=JSON.parse(await readFile(file,'utf8'));}
else{const rl=createInterface({input,output});const ask=async(label,fallback='')=>(await rl.question(`${label}${fallback?` [${fallback}]`:''}: `)).trim()||fallback;const companyName=await ask('Company Name','Aranya Buildcon');const logo=await ask('Logo path','/favicon.svg');const phone=await ask('Phone');const services=(await ask('Services, comma separated','Residential Construction, Commercial Construction, Turnkey Construction')).split(',').map(v=>v.trim()).filter(Boolean);const projects=(await ask('Projects, comma separated','Residential Project, Commercial Project')).split(',').map(v=>v.trim()).filter(Boolean);const primary=await ask('Primary Color','#c5944b');const secondary=await ask('Secondary Color','#192322');const accent=await ask('Accent Color','#ffffff');config={companyName,logo,phone,services,projects,colors:{primary,secondary,accent}};rl.close();}
for(const key of ['companyName','logo','phone','services','projects','colors'])if(config[key]==null)throw new Error(`Missing ${key}`);if(!Array.isArray(config.services)||!Array.isArray(config.projects))throw new Error('services and projects must be arrays.');for(const color of Object.values(config.colors))if(!/^#[0-9a-f]{6}$/i.test(String(color)))throw new Error('Colors must use six-digit hex values.');
let overwrite=true;try{await readFile(target);const rl=createInterface({input,output});overwrite=/^y(es)?$/i.test((await rl.question('client.config.ts exists. Replace it? [y/N]: ')).trim());rl.close()}catch{}if(!overwrite){console.log('Cancelled without changing client.config.ts.');process.exit(0)}
await writeFile(target,`export default ${JSON.stringify(config,null,2)} as const;\n`);console.log('Updated client.config.ts. Run npm run dev to review the client site.');
